//class CfgSounds {	
	class JTK_SIL_Rifle 
	{
		name = "SIL_Rifle";
		sound[] = {"\JTK\suppressors\sounds\SIL_Rifle.ogg",db-0.5,1}; 
		titles[] = {};
	};
	class JTK_SIL_Pistol 
	{
		name = "SIL_Pistol";
		sound[] = {"\JTK\suppressors\sounds\SIL_Rifle.ogg",db-0.5,1.5}; 
		titles[] = {};
	};
	class JTK_SIL_Reload 
	{
		name = "JTK_SIL_Reload";
		sound[] = {"\JTK\suppressors\sounds\Reload.ogg",db-0.5,1.5}; 
		titles[] = {};
	};
//};



