JTK_SIL_KeyDown_EH = {
	_handled = false;
	if ((_this select 1) == JTK_SL_Key) then {
		_handled = true; 
		JTK_SIL_KeyPressed = true;
	};
	_handled
};
JTK_SIL_KeyUp_EH = {
	_handled = false; 
	if ((_this select 1) == JTK_SL_Key) then {
		_handled = true; 
		JTK_SIL_KeyPressed = false;
	};
	_handled
};

JTK_SIL_Block_KeyDown_EH = {
	disableUserInput true;
	0.01 spawn {sleep _this; disableUserInput false};
	true
};

JTK_SIL_GetDelay = {
	_unit = _this select 0;
	_isPistol = _this select 1;
	if (_isPistol)exitWith {3.75};
	if (tolower(_unit getVariable "JTK_Current_Weapon") in JTK_SIL_SNPRS) exitWith {7.5};
	5
};



//Arrays
JTK_Snipers_West =  [
	"US_Delta_Force_Marksman_EP1",
	"US_Soldier_SniperH_EP1",
	"US_Soldier_Sniper_EP1",
	"US_Soldier_Sniper_NV_EP1",
	"USMC_SoldierS_Sniper",
	"USMC_SoldierS_SniperH",
	"FR_Marksman"
];
JTK_Delta_Force = [
	"US_Delta_Force_TL_EP1",
	"US_Delta_Force_MG_EP1",
	"US_Delta_Force_Assault_EP1",
	"US_Delta_Force_EP1",
	"US_Delta_Force_AR_EP1",
	"US_Delta_Force_M14_EP1",
	"US_Delta_Force_Medic_EP1",
	"US_Delta_Force_Marksman_EP1",
	"US_Delta_Force_EP1"
];
JTK_Force_Recon = [
	"FR_TL",
	"FR_Assault_R",
	"FR_Assault_GL",
	"FR_AR",
	"FR_Assault_R",
	"FR_Marksman",
	"FR_AR",
	"FR_Sapper",
	"FR_Assault_R",
	"FR_Assault_GL"
];
JTK_SF_West = JTK_Delta_Force + JTK_Force_Recon;



JTK_SIL_SNPRS = [
	"scar_h_lng_sniper",
	"scar_h_lng_sniper_sd",
	"m4spr",
	"ace_m4spr_sd",
	"ace_m110",
	"ace_m110_sd",
	"ace_mk12mod1",
	"ace_mk12mod1_sd",
	"ace_tac50",
	"ace_tac50_sd",
	"rh_hk417sp",
	"rh_hk417sdsp",
	"rh_mk14ebrsp",
	"rh_mk14ebrsp_sd",
	"rh_m14ebrsp",
	"rh_m14ebrsp_sd",
	"rh_mk21a5",
	"rh_mk21a5sd",	
	"rh_hk417sp",
	"rh_hk417sdsp",
	"rh_mk12",
	"rh_mk12sd",	
	"rh_mk12mod1",
	"rh_mk12sd",
	"fhq_rsass_tan",
	"fhq_rsass_sd_tan",
	"fhq_rsass_tws_tan",
	"fhq_rsass_tws_sd_tan",
	"fhq_rsass_nv_sd_tan",
	"fhq_xm2010_desert",
	"fhq_xm2010_sd_desert",
	"fhq_xm2010_nv_desert",
	"fhq_xm2010_nv_sd_desert",
	"fhq_xm2010_tws_desert",
	"fhq_xm2010_tws_sd_desert",
	"fhq_msr_desert",
	"fhq_msr_sd_desert",
	"fhq_msr_nv_desert",
	"fhq_msr_nv_sd_desert",
	"fhq_msr_tws_desert",
	"fhq_msr_tws_sd_desert"
];


JTK_ACEX_Weapons = [
	"ACE_AKMS",
	"ACE_AKMS_SD"
];


JTK_FHQ_Weapons = [	
	"FHQ_ACR_WDL_IRN",
	"FHQ_ACR_WDL_IRN_SD",
	"FHQ_ACR_WDL_IRN_F",
	"FHQ_ACR_WDL_IRN_SD_F",
	"FHQ_ACR_WDL_IRN_GL",
	"FHQ_ACR_WDL_IRN_GL_SD",
	"FHQ_ACR_WDL_IRN_GL_F",
	"FHQ_ACR_WDL_IRN_GL_SD_F",
	"FHQ_ACR_WDL_CCO",
	"FHQ_ACR_WDL_CCO_SD",
	"FHQ_ACR_WDL_CCO_F",
	"FHQ_ACR_WDL_CCO_SD_F",
	"FHQ_ACR_WDL_CCO_SD_F",
	"FHQ_ACR_WDL_CCO_GL",
	"FHQ_ACR_WDL_CCO_GL_SD",
	"FHQ_ACR_WDL_CCO_GL_F",
	"FHQ_ACR_WDL_CCO_GL_SD_F",
	"FHQ_ACR_WDL_RCO",
	"FHQ_ACR_WDL_RCO_SD",
	"FHQ_ACR_WDL_RCO_F",
	"FHQ_ACR_WDL_RCO_SD_F",
	"FHQ_ACR_WDL_RCO_GL",
	"FHQ_ACR_WDL_RCO_GL_SD",
	"FHQ_ACR_WDL_RCO_GL_F",
	"FHQ_ACR_WDL_HAMR_GL",
	"FHQ_ACR_WDL_HAMR_GL_SD",
	"FHQ_ACR_WDL_RCO_GL_SD_F",
	"FHQ_ACR_WDL_HWS",
	"FHQ_ACR_WDL_HWS_SD",
	"FHQ_ACR_WDL_HWS_F",
	"FHQ_ACR_WDL_HWS_SD_F",
	"FHQ_ACR_WDL_HWS_GL",
	"FHQ_ACR_WDL_HWS_GL_SD",
	"FHQ_ACR_WDL_HWS_GL_F",
	"FHQ_ACR_WDL_HWS_GL_SD_F",
	"FHQ_ACR_WDL_G33",
	"FHQ_ACR_WDL_G33_SD",
	"FHQ_ACR_WDL_G33_F",
	"FHQ_ACR_WDL_G33_SD_F",
	"FHQ_ACR_WDL_G33_GL",
	"FHQ_ACR_WDL_G33_GL_SD",
	"FHQ_ACR_WDL_G33_GL_F",
	"FHQ_ACR_WDL_G33_GL_SD_F",
	"FHQ_ACR_WDL_HAMR",
	"FHQ_ACR_WDL_HAMR_SD",
	"FHQ_ACR_WDL_HAMR_F",
	"FHQ_ACR_WDL_HAMR_SD_F",
	"FHQ_ACR_WDL_HAMR_GL_F",
	"FHQ_ACR_WDL_HAMR_GL_SD_F",
	
	"FHQ_ACR_BLK_IRN",
	"FHQ_ACR_BLK_IRN_SD",
	"FHQ_ACR_BLK_IRN_F",
	"FHQ_ACR_BLK_IRN_SD_F",
	"FHQ_ACR_BLK_IRN_GL",
	"FHQ_ACR_BLK_IRN_GL_SD",
	"FHQ_ACR_BLK_IRN_GL_F",
	"FHQ_ACR_BLK_IRN_GL_SD_F",
	"FHQ_ACR_BLK_CCO",
	"FHQ_ACR_BLK_CCO_SD",
	"FHQ_ACR_BLK_CCO_F",
	"FHQ_ACR_BLK_CCO_SD_F",
	"FHQ_ACR_BLK_CCO_SD_F",
	"FHQ_ACR_BLK_CCO_GL",
	"FHQ_ACR_BLK_CCO_GL_SD",
	"FHQ_ACR_BLK_CCO_GL_F",
	"FHQ_ACR_BLK_CCO_GL_SD_F",
	"FHQ_ACR_BLK_RCO",
	"FHQ_ACR_BLK_RCO_SD",
	"FHQ_ACR_BLK_RCO_F",
	"FHQ_ACR_BLK_RCO_SD_F",
	"FHQ_ACR_BLK_RCO_GL",
	"FHQ_ACR_BLK_RCO_GL_SD",
	"FHQ_ACR_BLK_RCO_GL_F",
	"FHQ_ACR_BLK_HAMR_GL",
	"FHQ_ACR_BLK_HAMR_GL_SD",
	"FHQ_ACR_BLK_RCO_GL_SD_F",
	"FHQ_ACR_BLK_HWS",
	"FHQ_ACR_BLK_HWS_SD",
	"FHQ_ACR_BLK_HWS_F",
	"FHQ_ACR_BLK_HWS_SD_F",
	"FHQ_ACR_BLK_HWS_GL",
	"FHQ_ACR_BLK_HWS_GL_SD",
	"FHQ_ACR_BLK_HWS_GL_F",
	"FHQ_ACR_BLK_HWS_GL_SD_F",
	"FHQ_ACR_BLK_G33",
	"FHQ_ACR_BLK_G33_SD",
	"FHQ_ACR_BLK_G33_F",
	"FHQ_ACR_BLK_G33_SD_F",
	"FHQ_ACR_BLK_G33_GL",
	"FHQ_ACR_BLK_G33_GL_SD",
	"FHQ_ACR_BLK_G33_GL_F",
	"FHQ_ACR_BLK_G33_GL_SD_F",
	"FHQ_ACR_BLK_HAMR",
	"FHQ_ACR_BLK_HAMR_SD",
	"FHQ_ACR_BLK_HAMR_F",
	"FHQ_ACR_BLK_HAMR_SD_F",
	"FHQ_ACR_BLK_HAMR_GL_F",
	"FHQ_ACR_BLK_HAMR_GL_SD_F",
	
	"FHQ_ACR_TAN_IRN",
	"FHQ_ACR_TAN_IRN_SD",
	"FHQ_ACR_TAN_IRN_F",
	"FHQ_ACR_TAN_IRN_SD_F",
	"FHQ_ACR_TAN_IRN_GL",
	"FHQ_ACR_TAN_IRN_GL_SD",
	"FHQ_ACR_TAN_IRN_GL_F",
	"FHQ_ACR_TAN_IRN_GL_SD_F",
	"FHQ_ACR_TAN_CCO",
	"FHQ_ACR_TAN_CCO_SD",
	"FHQ_ACR_TAN_CCO_F",
	"FHQ_ACR_TAN_CCO_SD_F",
	"FHQ_ACR_TAN_CCO_SD_F",
	"FHQ_ACR_TAN_CCO_GL",
	"FHQ_ACR_TAN_CCO_GL_SD",
	"FHQ_ACR_TAN_CCO_GL_F",
	"FHQ_ACR_TAN_CCO_GL_SD_F",
	"FHQ_ACR_TAN_RCO",
	"FHQ_ACR_TAN_RCO_SD",
	"FHQ_ACR_TAN_RCO_F",
	"FHQ_ACR_TAN_RCO_SD_F",
	"FHQ_ACR_TAN_RCO_GL",
	"FHQ_ACR_TAN_RCO_GL_SD",
	"FHQ_ACR_TAN_RCO_GL_F",
	"FHQ_ACR_TAN_HAMR_GL",
	"FHQ_ACR_TAN_HAMR_GL_SD",
	"FHQ_ACR_TAN_RCO_GL_SD_F",
	"FHQ_ACR_TAN_HWS",
	"FHQ_ACR_TAN_HWS_SD",
	"FHQ_ACR_TAN_HWS_F",
	"FHQ_ACR_TAN_HWS_SD_F",
	"FHQ_ACR_TAN_HWS_GL",
	"FHQ_ACR_TAN_HWS_GL_SD",
	"FHQ_ACR_TAN_HWS_GL_F",
	"FHQ_ACR_TAN_HWS_GL_SD_F",
	"FHQ_ACR_TAN_G33",
	"FHQ_ACR_TAN_G33_SD",
	"FHQ_ACR_TAN_G33_F",
	"FHQ_ACR_TAN_G33_SD_F",
	"FHQ_ACR_TAN_G33_GL",
	"FHQ_ACR_TAN_G33_GL_SD",
	"FHQ_ACR_TAN_G33_GL_F",
	"FHQ_ACR_TAN_G33_GL_SD_F",
	"FHQ_ACR_TAN_HAMR",
	"FHQ_ACR_TAN_HAMR_SD",
	"FHQ_ACR_TAN_HAMR_F",
	"FHQ_ACR_TAN_HAMR_SD_F",
	"FHQ_ACR_TAN_HAMR_GL_F",
	"FHQ_ACR_TAN_HAMR_GL_SD_F",
	
	"FHQ_ACR_SNW_IRN",
	"FHQ_ACR_SNW_IRN_SD",
	"FHQ_ACR_SNW_IRN_F",
	"FHQ_ACR_SNW_IRN_SD_F",
	"FHQ_ACR_SNW_IRN_GL",
	"FHQ_ACR_SNW_IRN_GL_SD",
	"FHQ_ACR_SNW_IRN_GL_F",
	"FHQ_ACR_SNW_IRN_GL_SD_F",
	"FHQ_ACR_SNW_CCO",
	"FHQ_ACR_SNW_CCO_SD",
	"FHQ_ACR_SNW_CCO_F",
	"FHQ_ACR_SNW_CCO_SD_F",
	"FHQ_ACR_SNW_CCO_SD_F",
	"FHQ_ACR_SNW_CCO_GL",
	"FHQ_ACR_SNW_CCO_GL_SD",
	"FHQ_ACR_SNW_CCO_GL_F",
	"FHQ_ACR_SNW_CCO_GL_SD_F",
	"FHQ_ACR_SNW_RCO",
	"FHQ_ACR_SNW_RCO_SD",
	"FHQ_ACR_SNW_RCO_F",
	"FHQ_ACR_SNW_RCO_SD_F",
	"FHQ_ACR_SNW_RCO_GL",
	"FHQ_ACR_SNW_RCO_GL_SD",
	"FHQ_ACR_SNW_RCO_GL_F",
	"FHQ_ACR_SNW_HAMR_GL",
	"FHQ_ACR_SNW_HAMR_GL_SD",
	"FHQ_ACR_SNW_RCO_GL_SD_F",
	"FHQ_ACR_SNW_HWS",
	"FHQ_ACR_SNW_HWS_SD",
	"FHQ_ACR_SNW_HWS_F",
	"FHQ_ACR_SNW_HWS_SD_F",
	"FHQ_ACR_SNW_HWS_GL",
	"FHQ_ACR_SNW_HWS_GL_SD",
	"FHQ_ACR_SNW_HWS_GL_F",
	"FHQ_ACR_SNW_HWS_GL_SD_F",
	"FHQ_ACR_SNW_G33",
	"FHQ_ACR_SNW_G33_SD",
	"FHQ_ACR_SNW_G33_F",
	"FHQ_ACR_SNW_G33_SD_F",
	"FHQ_ACR_SNW_G33_GL",
	"FHQ_ACR_SNW_G33_GL_SD",
	"FHQ_ACR_SNW_G33_GL_F",
	"FHQ_ACR_SNW_G33_GL_SD_F",
	"FHQ_ACR_SNW_HAMR",
	"FHQ_ACR_SNW_HAMR_SD",
	"FHQ_ACR_SNW_HAMR_F",
	"FHQ_ACR_SNW_HAMR_SD_F",
	"FHQ_ACR_SNW_HAMR_GL_F",
	"FHQ_ACR_SNW_HAMR_GL_SD_F",
	
	"FHQ_RSASS_TAN",
	"FHQ_RSASS_SD_TAN",
	"FHQ_RSASS_TWS_TAN",
	"FHQ_RSASS_TWS_SD_TAN",
	"FHQ_RSASS_NV_TAN",
	"FHQ_RSASS_NV_SD_TAN",
	"FHQ_XM2010_DESERT",
	"FHQ_XM2010_SD_DESERT",
	"FHQ_XM2010_NV_DESERT",
	"FHQ_XM2010_NV_SD_DESERT",
	"FHQ_XM2010_TWS_DESERT",
	"FHQ_XM2010_TWS_SD_DESERT",
	"FHQ_MSR_DESERT",
	"FHQ_MSR_SD_DESERT",
	"FHQ_MSR_NV_DESERT",
	"FHQ_MSR_NV_SD_DESERT",
	"FHQ_MSR_TWS_DESERT",
	"FHQ_MSR_TWS_SD_DESERT"
];


