class JTK_Identity_1 {
	name = "$STR_Anything"; 
	face = "face01"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
}
class JTK_Identity_2 {
	name = "$STR_Anything";
	face = "face02"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
}
class JTK_Identity_3 {
	name = "$STR_Anything"; 
	face = "face03"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
}
class JTK_Identity_4 {
	name = "$STR_Anything";
	face = "face04"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_5 {
	name = "$STR_Anything";
	face = "face05"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_6 {
	name = "$STR_Anything";
	face = "face06"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_7 {
	name = "$STR_Anything";
	face = "face07"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_8 {
	name = "$STR_Anything"; 
	face = "face08"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_9 {
	name = "$STR_Anything"; 
	face = "face09"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_10 {
	name = "$STR_Anything"; 
	face = "face10"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_11 {
	name = "$STR_Anything"; 
	face = "face11"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_12 {
	name = "$STR_Anything";  
	face = "face12"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_13 {
	name = "$STR_Anything"; 
	face = "face13"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_14 {
	name = "$STR_Anything";  
	face = "face14"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_15 {
	name = "$STR_Anything"; 
	face = "face15"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_16 {
	name = "$STR_Anything";  
	face = "face16"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_17 {
	name = "$STR_Anything";  
	face = "face17"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_18 {
	name = "$STR_Anything";  
	face = "face18"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_19 {
	name = "$STR_Anything";  
	face = "face19"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_20 {
	name = "$STR_Anything";  
	face = "face20"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_21 {
	name = "$STR_Anything"; 
	face = "face21"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_22 {
	name = "$STR_Anything";  
	face = "face22"; 
	glasses = "None";
	speaker = "Male01EN";
	pitch = 1;
};
class JTK_Identity_23 {
	name = "$STR_Anything";  
	face = "face23"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_24 {
	name = "$STR_Anything"; 
	face = "face24"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_25 {
	name = "$STR_Anything";  
	face = "face25"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};

//Goggles and Cammo
class JTK_Identity_G1 {
	name = "$STR_Anything"; 
	face = "face01"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
}
class JTK_Identity_G2 {
	name = "$STR_Anything";
	face = "face02"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
}
class JTK_Identity_G3 {
	name = "$STR_Anything"; 
	face = "face03"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
}
class JTK_Identity_G4 {
	name = "$STR_Anything";
	face = "face04"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G5 {
	name = "$STR_Anything";
	face = "face05"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G6 {
	name = "$STR_Anything";
	face = "face06"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G7 {
	name = "$STR_Anything";
	face = "face07"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G8 {
	name = "$STR_Anything"; 
	face = "face08"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G9 {
	name = "$STR_Anything"; 
	face = "face09"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G10 {
	name = "$STR_Anything"; 
	face = "face10"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G11 {
	name = "$STR_Anything"; 
	face = "face11"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G12 {
	name = "$STR_Anything";  
	face = "face12"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G13 {
	name = "$STR_Anything"; 
	face = "face13"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G14 {
	name = "$STR_Anything";  
	face = "face14"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G15 {
	name = "$STR_Anything"; 
	face = "face15"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G16 {
	name = "$STR_Anything";  
	face = "face16"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G17 {
	name = "$STR_Anything";  
	face = "face17"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G18 {
	name = "$STR_Anything";  
	face = "face18"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G19 {
	name = "$STR_Anything";  
	face = "face19"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G20 {
	name = "$STR_Anything";  
	face = "face20"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G21 {
	name = "$STR_Anything"; 
	face = "face21"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G22 {
	name = "$STR_Anything";  
	face = "face22"; 
	glasses = "Delta_glasses";
	speaker = "Male01EN";
	pitch = 1;
};
class JTK_Identity_G23 {
	name = "$STR_Anything";  
	face = "face23"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G24 {
	name = "$STR_Anything"; 
	face = "face24"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_G25 {
	name = "$STR_Anything";  
	face = "face25"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};


	
class JTK_Identity_Cammo_1 {
	name = "$STR_Anything"; 
	face = "face01_camo1"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
}
class JTK_Identity_Cammo_2 {
	name = "$STR_Anything";
	face = "face02_camo2"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
}
class JTK_Identity_Cammo_3 {
	name = "$STR_Anything"; 
	face = "face03_camo3"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
}
class JTK_Identity_Cammo_4 {
	name = "$STR_Anything";
	face = "face04_camo4"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_5 {
	name = "$STR_Anything";
	face = "face05_camo5"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_6 {
	name = "$STR_Anything";
	face = "face06_camo6"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_7 {
	name = "$STR_Anything";
	face = "face07_camo1"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_8 {
	name = "$STR_Anything"; 
	face = "face08_camo2"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_9 {
	name = "$STR_Anything"; 
	face = "face09_camo3"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_10 {
	name = "$STR_Anything"; 
	face = "face10_camo4"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_11 {
	name = "$STR_Anything"; 
	face = "face11_camo5"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_12 {
	name = "$STR_Anything";  
	face = "face12_camo6"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_13 {
	name = "$STR_Anything"; 
	face = "face13_camo1"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_14 {
	name = "$STR_Anything";  
	face = "face14_camo2"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_15 {
	name = "$STR_Anything"; 
	face = "face15_camo3"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_16 {
	name = "$STR_Anything";  
	face = "face16_camo4"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_17 {
	name = "$STR_Anything";  
	face = "face17_camo5"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_18 {
	name = "$STR_Anything";  
	face = "face18_camo6"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_19 {
	name = "$STR_Anything";  
	face = "face19_camo1"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_20 {
	name = "$STR_Anything";  
	face = "face20_camo2"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_21 {
	name = "$STR_Anything"; 
	face = "face21_camo3"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_22 {
	name = "$STR_Anything";  
	face = "face22_camo4"; 
	glasses = "None";
	speaker = "Male01EN";
	pitch = 1;
};
class JTK_Identity_Cammo_23 {
	name = "$STR_Anything";  
	face = "face23_camo5"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_24 {
	name = "$STR_Anything"; 
	face = "face24_camo6"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_25 {
	name = "$STR_Anything";  
	face = "face25_camo1"; 
	glasses = "None"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
//Goggles and Cammo
class JTK_Identity_Cammo_G1 {
	name = "$STR_Anything"; 
	face = "face01_camo1"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
}
class JTK_Identity_Cammo_G2 {
	name = "$STR_Anything";
	face = "face02_camo2"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
}
class JTK_Identity_Cammo_G3 {
	name = "$STR_Anything"; 
	face = "face03_camo3"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
}
class JTK_Identity_Cammo_G4 {
	name = "$STR_Anything";
	face = "face04_camo4"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G5 {
	name = "$STR_Anything";
	face = "face05_camo5"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G6 {
	name = "$STR_Anything";
	face = "face06_camo6"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G7 {
	name = "$STR_Anything";
	face = "face07_camo1"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G8 {
	name = "$STR_Anything"; 
	face = "face08_camo2"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G9 {
	name = "$STR_Anything"; 
	face = "face09_camo3"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G10 {
	name = "$STR_Anything"; 
	face = "face10_camo4"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G11 {
	name = "$STR_Anything"; 
	face = "face11_camo5"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G12 {
	name = "$STR_Anything";  
	face = "face12_camo6"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G13 {
	name = "$STR_Anything"; 
	face = "face13_camo1"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G14 {
	name = "$STR_Anything";  
	face = "face14_camo2"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G15 {
	name = "$STR_Anything"; 
	face = "face15_camo3"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G16 {
	name = "$STR_Anything";  
	face = "face16_camo4"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G17 {
	name = "$STR_Anything";  
	face = "face17_camo5"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G18 {
	name = "$STR_Anything";  
	face = "face18_camo6"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G19 {
	name = "$STR_Anything";  
	face = "face19_camo1"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G20 {
	name = "$STR_Anything";  
	face = "face20_camo2"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G21 {
	name = "$STR_Anything"; 
	face = "face21_camo3"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G22 {
	name = "$STR_Anything";  
	face = "face22_camo4"; 
	glasses = "Delta_glasses";
	speaker = "Male01EN";
	pitch = 1;
};
class JTK_Identity_Cammo_G23 {
	name = "$STR_Anything";  
	face = "face23_camo5"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G24 {
	name = "$STR_Anything"; 
	face = "face24_camo6"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};
class JTK_Identity_Cammo_G25 {
	name = "$STR_Anything";  
	face = "face25_camo1"; 
	glasses = "Delta_glasses"; 
	speaker = "Male01EN"; 
	pitch = 1;
};	

